name = "qr-code-attendance-worker"
type = "javascript"
account_id = "your-cloudflare-account-id"
workers_dev = true

[[durable_objects]]
binding = "ATTENDANCE_OBJECT"
class_name = "AttendanceDurableObject"
