name = "qr-code-attendance-worker"
type = "javascript"

main = "/workers/worker.js"

account_id = "360dc20d79673a3ee77c326c98e2acb5"
compatibility_date = "2024-10-07"

[[kv_namespaces]]
binding = "ATTENDANCE"
id = "c59683167fd9472e8de8bb0200f96f17"
